### ISSUE TITLE
BOT CRASHES

### ISSUE THREAD

**Issue by fardeen619** [kabirsingh2004/lavalink-music-bot-2021#1]
This source code crashes every in hour. it disconnects from discord websocket
tell me what is the problem and how to solve

**Comment by kabirsingh2004** [comment]
use your own lavalink server
and host on best vps

**Comment by fardeen619** [comment]
Bhai milrato ki copy karna band krde kuch apna bana

**Comment by kabirsingh2004** [comment]
> Bhai milrato ki copy karna band krde kuch apna bana

purana h ab chhod diya
